Tema Abastracción con Ruby
sistemas-sw/impl-24 pull request #12
Opened 2024-04-29 20:25 UTC by PabloAC04

Ya he completado el tema Abstracción con Ruby, he intentado controlar todo de tal manera que no haya conflictos. Además podrás apreciar que he creado un par de issues uno manual y el otro automático mediante la Acción de GitHub. El segundo lo he gestionado con una rama hotfix como hemos visto hoy en clase. Espero cualquier anotación sobre el tema si ve algo que no le agrade.

2024-04-30 07:31 UTC, dodero requested changes
El fichero de workflow, en este caso, debe llamarse `abstraccion.ruby.yml`

2024-04-30 08:57 UTC, PabloAC04 commented
Ya he cambiado el nombre del fichero de workflow.

2024-05-02 16:02 UTC, merged

2024-05-03 07:31 UTC, dodero commented
Las actions de Node.js 16 están obsoletas. Puedes actualizar `actions/checkout@v3` para que use Node.js 20. Más info en: 
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

2024-05-03 07:51 UTC, dodero commented on temas/abstraccion/ruby/README.md
Vendría bien una pequeña explicación del significado de los mecanismos que has usado de Ruby (`module`, atributos `@`, `require`, etc.) y cómo se mapean a los conceptos teóricos que hemos visto relacionados con la abstracción en las clases de teoría.

2024-05-03 09:28 UTC, dodero commented
Al ejecutar `terraform apply`, se queda indefinidamente en:
```
docker_image.app_image: Creating...
docker_image.app_image: Still creating... [10s elapsed]
docker_image.app_image: Still creating... [20s elapsed]
docker_image.app_image: Still creating... [30s elapsed]
docker_image.app_image: Still creating... [40s elapsed]
```