Modificación de ejemplo de errores
sistemas-sw/impl-24 pull request #21
Opened 2024-05-06 17:00 UTC by martaajonees

2024-05-06 17:24 UTC, dodero commented
Resolver conflictos...

2024-05-06 18:20 UTC, martaajonees commented
Conflictos resueltos

2024-05-09 06:41 UTC, dodero requested changes

2024-05-09 06:41 UTC, dodero commented on .github/workflows/main.yml
Este fichero no cumple las normas de nombrado. Renombrar o suprimir

2024-05-09 06:41 UTC, dodero commented on temas/errores/ruby/.terraform/providers/registry.terraform.io/hashicorp/null/3.2.2/darwin_amd64/terraform-provider-null_v3.2.2_x5
Eliminar este fichero del repo

2024-05-09 06:43 UTC, merged